### PR TITLE
fix: reposition labels for partially visible frames. See bug #33.

### LINKED ISSUE #33: When zooming on a frame, display text for lrger parent frames
Example where text could be added:

image

### PR DESCRIPTION
**Pull request by jfree**
Fixes #33.  When a frame is only partially visible its label can be hidden - in these cases, switch the font to italics and render the label at the left side of the visible part of the frame.  For example:
image

### CODE REVIEW

File: fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraphPainter.java [hunk 1]
```diff
@@ -60,11 +66,14 @@
...
     protected boolean paintDetails = true;
 
-
     public FlameGraphPainter(List<FrameBox<T>> frames,
                              List<Function<T, String>> nodeToTextCandidates,
                              Function<T, String> rootFrameToText,
                              Function<T, Color> frameColorFunction) {
+
+        this.frameLabelFont = new Font(Font.SANS_SERIF, Font.PLAIN, 12);
+        this.frameLabelFontItalic = new Font(Font.SANS_SERIF, Font.ITALIC, 12);
```
Comment (bric3) [inline fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraphPainter.java:75]: I'd rather name about the intent of this font, not sure about the name something like : `largerFrameLabelFont`

File: fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraphPainter.java [hunk 2]
```diff
@@ -384,7 +440,7 @@ public void stopHover() {
     }
 
     private void paintFrameText(T node, Graphics2D g2, double targetWidth, Consumer<String> textConsumer) {
-        var metrics = g2.getFontMetrics();
+        var metrics = g2.getFontMetrics(frameLabelFont);
```
Comment (bric3) [inline fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraphPainter.java:443]: Shouldn't it pick the current font like the other `paintFrameText` method ?

**Review by bric3 — APPROVED** [review]
Nice improvement

File: fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraphPainter.java (hunk 2 above)
Comment (jfree) [reply fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraphPainter.java:443]: I don't think there is a right answer here, since the `textConsumer` ultimately sets the font.  But `frameLabelFont` is probably a good reflection of the intent.

Comment (bric3) [reply fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraphPainter.java:443]: Indeed but that's the caller of this method that controls the font and the consumer.

Comment (jfree) [reply fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraphPainter.java:443]: Ah, the static version of the method has a `font` parameter, while this one doesn't.  I'll add it.

File: fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraphPainter.java (hunk 1 above)
Comment (jfree) [reply fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraphPainter.java]: I changed the name to `frameLabelFontForPartialFrames`

File: fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraphPainter.java (hunk 2 above)
Comment (jfree) [reply fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraphPainter.java]: Done.

**Review by bric3 — APPROVED** [review]

**Review by bric3 — APPROVED** [review]
