### PR TITLE
fix: check for null hoveringListener, fixes #49.

### LINKED ISSUE #49: NullPointerException related to hover listener
When I run `FirePlaceMain` and view the `Allocations` flame graph I observe the following `NullPointerException`:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "io.github.bric3.fireplace.flamegraph.FlameGraph$HoveringListener.onFrameHover(io.github.bric3.fireplace.flamegraph.FrameBox, java.awt.Rectangle, java.awt.event.MouseEvent)" because "this.hoveringListener" is null
	at io.github.bric3.fireplace.flamegraph.FlameGraph$FlameGraphMouseInputListener.mouseMoved(FlameGraph.java:471)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6671)
	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3407)
	at java.desktop/java.awt.Component.processEvent(Component.java:6395)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at io.github.bric3.fireplace.core.ui.MouseInputListenerWorkaroundForToolTipEnabledComponent.dispatch(MouseInputListenerWorkaroundForToolTipEnabledComponent.java:57)
	at io.github.bric3.fireplace.core.ui.MouseInputListenerWorkaroundForToolTipEnabledComponent.mouseMoved(MouseInputListenerWorkaroundForToolTipEnabledComponent.java:99)
	at java.desktop/java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:337)
	at java.desktop/java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:337)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6671)
	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3407)
	at java.desktop/java.awt.Component.processEvent(Component.java:6395)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4588)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

The fix is simple, PR is coming.

### PR DESCRIPTION
**Pull request by jfree**
Adds a couple of `null` checks to fix issue #49.

### CODE REVIEW

File: fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraph.java [hunk 1]
```diff
@@ -459,7 +459,9 @@ public void mouseMoved(MouseEvent e) {
             SwingUtilities.convertPointFromScreen(latestMouseLocation, canvas);
 
             if (this.canvas.isInsideMinimap(latestMouseLocation)) {
-                hoveringListener.onStopHover(e);
+                if (hoveringListener != null) {
+                    hoveringListener.onStopHover(e);
+                }
```
Comment (bric3) [inline fireplace-swing/src/main/java/io/github/bric3/fireplace/flamegraph/FlameGraph.java:464]: 😅 oh the billion dollar stupid mistake

**Review by bric3 — APPROVED** [review]
